// <auto-generated />
using System;
using FourierIT_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FourierIT_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260508123729_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FourierIT_API.Models.AccessList", b =>
                {
                    b.Property<int>("EnquiryRequestId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<int>("EnquiryId")
                        .HasColumnType("int");

                    b.HasKey("EnquiryRequestId", "DocumentId", "EnquiryId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("EnquiryId");

                    b.ToTable("AccessList");
                });

            modelBuilder.Entity("FourierIT_API.Models.AccessToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TokenId"));

                    b.Property<int>("EnquiryRequestId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ExpiryTimeStamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("TokenString")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TokenId");

                    b.HasIndex("EnquiryRequestId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AccessToken");
                });

            modelBuilder.Entity("FourierIT_API.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<int>("SuburbId")
                        .HasColumnType("int");

                    b.HasKey("AddressId");

                    b.HasIndex("SuburbId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("FourierIT_API.Models.BlobHistory", b =>
                {
                    b.Property<int>("BlobHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlobHistoryId"));

                    b.Property<string>("ActionTaken")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("ArchivedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DocumentBlobId")
                        .HasColumnType("int");

                    b.HasKey("BlobHistoryId");

                    b.HasIndex("DocumentBlobId");

                    b.ToTable("BlobHistory");
                });

            modelBuilder.Entity("FourierIT_API.Models.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("int");

                    b.HasKey("BranchId");

                    b.HasIndex("InstitutionId");

                    b.ToTable("Branch");
                });

            modelBuilder.Entity("FourierIT_API.Models.CertificationDetails", b =>
                {
                    b.Property<string>("CertificationID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CertificationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CommissionerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.HasKey("CertificationID");

                    b.HasIndex("DocumentId");

                    b.ToTable("CertificationDetails");
                });

            modelBuilder.Entity("FourierIT_API.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("CityId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("FourierIT_API.Models.ClientEnlistment", b =>
                {
                    b.Property<int>("ClientEnlistmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientEnlistmentId"));

                    b.Property<DateTimeOffset>("EnlistmentDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EnlistmentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ClientEnlistmentId");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("UserId");

                    b.ToTable("ClientEnlistment");
                });

            modelBuilder.Entity("FourierIT_API.Models.ClientRiskRating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"));

                    b.Property<int>("ClientEnlistmentId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RatingId");

                    b.HasIndex("ClientEnlistmentId")
                        .IsUnique();

                    b.ToTable("ClientRiskRating");
                });

            modelBuilder.Entity("FourierIT_API.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("DepartmentId");

                    b.HasIndex("BranchId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("FourierIT_API.Models.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ExpiryDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsCertified")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DocumentId");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("FourierIT_API.Models.DocumentBlob", b =>
                {
                    b.Property<int>("DocumentBlobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentBlobId"));

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasMaxLength(50485760)
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("DocumentBlobId");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.ToTable("DocumentBlob");
                });

            modelBuilder.Entity("FourierIT_API.Models.DocumentFicaRule", b =>
                {
                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<int>("FICARuleId")
                        .HasColumnType("int");

                    b.HasKey("DocumentTypeId", "FICARuleId");

                    b.HasIndex("FICARuleId");

                    b.ToTable("DocumentFicaRule");
                });

            modelBuilder.Entity("FourierIT_API.Models.DocumentStatusHistory", b =>
                {
                    b.Property<int>("StatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusHistoryId"));

                    b.Property<DateTimeOffset>("DateArchived")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("StatusHistoryId");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentStatusHistory");
                });

            modelBuilder.Entity("FourierIT_API.Models.DocumentType", b =>
                {
                    b.Property<int>("DocumentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentTypeId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DocumentTypeId");

                    b.ToTable("DocumentType");
                });

            modelBuilder.Entity("FourierIT_API.Models.EnquiryComment", b =>
                {
                    b.Property<int>("EnquiryCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnquiryCommentId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EnquiryFlagId")
                        .HasColumnType("int");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EnquiryCommentId");

                    b.HasIndex("EnquiryFlagId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("EnquiryComment");
                });

            modelBuilder.Entity("FourierIT_API.Models.EnquiryFlag", b =>
                {
                    b.Property<int>("EnquiryFlagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnquiryFlagId"));

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<int>("EnquiryId")
                        .HasColumnType("int");

                    b.Property<string>("FlagReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.HasKey("EnquiryFlagId");

                    b.ToTable("EnquiryFlag");
                });

            modelBuilder.Entity("FourierIT_API.Models.EnquirySession", b =>
                {
                    b.Property<int>("EnquirySessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnquirySessionId"));

                    b.Property<TimeOnly>("SessionEndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("SessionStartTime")
                        .HasColumnType("time");

                    b.Property<int>("TokenId")
                        .HasColumnType("int");

                    b.HasKey("EnquirySessionId");

                    b.HasIndex("TokenId")
                        .IsUnique();

                    b.ToTable("EnquirySession");
                });

            modelBuilder.Entity("FourierIT_API.Models.FICARule", b =>
                {
                    b.Property<int>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RuleId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ValidityMonths")
                        .HasColumnType("int");

                    b.HasKey("RuleId");

                    b.ToTable("FICARule");
                });

            modelBuilder.Entity("FourierIT_API.Models.FICARuleHistory", b =>
                {
                    b.Property<int>("RuleHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RuleHistoryId"));

                    b.Property<DateTimeOffset>("DateChanged")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RuleId")
                        .HasColumnType("int");

                    b.HasKey("RuleHistoryId");

                    b.HasIndex("RuleId");

                    b.ToTable("FICARuleHistory");
                });

            modelBuilder.Entity("FourierIT_API.Models.Institution", b =>
                {
                    b.Property<int>("InstitutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstitutionId"));

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("RegNumber")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<string>("VerifiedDomain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("InstitutionId");

                    b.HasIndex("TypeId");

                    b.ToTable("Institution");
                });

            modelBuilder.Entity("FourierIT_API.Models.InstitutionEnquiryRequest", b =>
                {
                    b.Property<int>("EnquiryRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnquiryRequestId"));

                    b.Property<int>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<string>("PurposeNote")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("RequestDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("EnquiryRequestId");

                    b.HasIndex("InstitutionId");

                    b.ToTable("InstitutionEnquiryRequest");
                });

            modelBuilder.Entity("FourierIT_API.Models.InstitutionMembers", b =>
                {
                    b.Property<int>("MembersId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("MembersId", "UserId", "InstitutionId");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("UserId");

                    b.ToTable("InstitutionMembers");
                });

            modelBuilder.Entity("FourierIT_API.Models.InstitutionType", b =>
                {
                    b.Property<int>("InstitutionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstitutionTypeId"));

                    b.Property<string>("InstitutionTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("InstitutionTypeId");

                    b.ToTable("InstitutionType");
                });

            modelBuilder.Entity("FourierIT_API.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("NotificationId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("FourierIT_API.Models.NotificationHistory", b =>
                {
                    b.Property<int>("NotificationHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationHistoryId"));

                    b.Property<string>("DeliveryMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NotificationId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("NotificationHistoryId");

                    b.HasIndex("NotificationId");

                    b.ToTable("NotificationHistory");
                });

            modelBuilder.Entity("FourierIT_API.Models.Profile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfileId"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProfileId");

                    b.HasIndex("AddressId")
                        .IsUnique()
                        .HasFilter("[AddressId] IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("FourierIT_API.Models.Province", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProvinceId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProvinceId");

                    b.ToTable("Province");
                });

            modelBuilder.Entity("FourierIT_API.Models.RiskHistory", b =>
                {
                    b.Property<int>("RiskHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RiskHistoryId"));

                    b.Property<int>("ClientRiskRatingId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("RecordedDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("ScoreAtTime")
                        .HasColumnType("time");

                    b.HasKey("RiskHistoryId");

                    b.HasIndex("ClientRiskRatingId");

                    b.ToTable("RiskHistory");
                });

            modelBuilder.Entity("FourierIT_API.Models.RiskRatingVariable", b =>
                {
                    b.Property<int>("RatingId")
                        .HasColumnType("int");

                    b.Property<int>("RiskVariableId")
                        .HasColumnType("int");

                    b.HasKey("RatingId", "RiskVariableId");

                    b.HasIndex("RiskVariableId");

                    b.ToTable("RiskRatingVariable");
                });

            modelBuilder.Entity("FourierIT_API.Models.RiskVariable", b =>
                {
                    b.Property<int>("RiskVariableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RiskVariableId"));

                    b.Property<string>("VarName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("WeightMultiplier")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RiskVariableId");

                    b.ToTable("RiskVariable");
                });

            modelBuilder.Entity("FourierIT_API.Models.SecurityQuestion", b =>
                {
                    b.Property<int>("SecurityQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SecurityQuestionId"));

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("SecurityQuestionId");

                    b.ToTable("SecurityQuestion");
                });

            modelBuilder.Entity("FourierIT_API.Models.Suburb", b =>
                {
                    b.Property<int>("SuburbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuburbId"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAtRisk")
                        .HasColumnType("bit");

                    b.Property<string>("SuburbName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SuburbId");

                    b.HasIndex("CityId");

                    b.ToTable("Suburb");
                });

            modelBuilder.Entity("FourierIT_API.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("FailedLoginAttempts")
                        .HasMaxLength(500)
                        .HasColumnType("int");

                    b.Property<bool>("HasAccessToken")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPEPStatus")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("MfaEnabled")
                        .HasMaxLength(100)
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FourierIT_API.Models.UserNotification", b =>
                {
                    b.Property<int>("NotificationId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.HasKey("NotificationId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserNotification");
                });

            modelBuilder.Entity("FourierIT_API.Models.UserSecurityQuestion", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SecurityQuestionId")
                        .HasColumnType("int");

                    b.Property<string>("EncryptedAnswer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("UserId", "SecurityQuestionId");

                    b.HasIndex("SecurityQuestionId");

                    b.ToTable("UserSecurityQuestion");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "975239e2-7687-4df5-a05a-ca96532d4337",
                            Name = "Department Admin",
                            NormalizedName = "DEPARTMENT ADMIN"
                        },
                        new
                        {
                            Id = "949763de-b3c2-408d-92b0-b56d27259831",
                            Name = "Document Owner",
                            NormalizedName = "DOCUMENT OWNER"
                        },
                        new
                        {
                            Id = "7cf85b78-3887-44c4-aac7-840e14b391e2",
                            Name = "Stakeholder",
                            NormalizedName = "STAKEHOLDER"
                        },
                        new
                        {
                            Id = "b798abf3-d098-4f9d-9c13-04d5100b403e",
                            Name = "Compliance Officer",
                            NormalizedName = "COMPLIANCE OFFICER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FourierIT_API.Models.AccessList", b =>
                {
                    b.HasOne("FourierIT_API.Models.Document", "Document")
                        .WithMany("AccessLists")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FourierIT_API.Models.EnquiryFlag", "EnquiryFlag")
                        .WithMany("AccessLists")
                        .HasForeignKey("EnquiryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FourierIT_API.Models.InstitutionEnquiryRequest", "InstitutionEnquiryRequest")
                        .WithMany("AccessLists")
                        .HasForeignKey("EnquiryRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("EnquiryFlag");

                    b.Navigation("InstitutionEnquiryRequest");
                });

            modelBuilder.Entity("FourierIT_API.Models.AccessToken", b =>
                {
                    b.HasOne("FourierIT_API.Models.InstitutionEnquiryRequest", "institutionEnquiryRequest")
                        .WithOne("AccessToken")
                        .HasForeignKey("FourierIT_API.Models.AccessToken", "EnquiryRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FourierIT_API.Models.User", "User")
                        .WithOne("AccessToken")
                        .HasForeignKey("FourierIT_API.Models.AccessToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("institutionEnquiryRequest");
                });

            modelBuilder.Entity("FourierIT_API.Models.Address", b =>
                {
                    b.HasOne("FourierIT_API.Models.Suburb", "Suburb")
                        .WithMany("Addresses")
                        .HasForeignKey("SuburbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Suburb");
                });

            modelBuilder.Entity("FourierIT_API.Models.BlobHistory", b =>
                {
                    b.HasOne("FourierIT_API.Models.DocumentBlob", "DocumentBlob")
                        .WithMany("BlobHistories")
                        .HasForeignKey("DocumentBlobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentBlob");
                });

            modelBuilder.Entity("FourierIT_API.Models.Branch", b =>
                {
                    b.HasOne("FourierIT_API.Models.Institution", "Institution")
                        .WithMany("Branches")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("FourierIT_API.Models.CertificationDetails", b =>
                {
                    b.HasOne("FourierIT_API.Models.Document", "Document")
                        .WithMany("CertificationDetails")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("FourierIT_API.Models.City", b =>
                {
                    b.HasOne("FourierIT_API.Models.Province", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("FourierIT_API.Models.ClientEnlistment", b =>
                {
                    b.HasOne("FourierIT_API.Models.Institution", "Institution")
                        .WithMany("ClientEnlistments")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FourierIT_API.Models.User", "User")
                        .WithMany("ClientEnlistments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FourierIT_API.Models.ClientRiskRating", b =>
                {
                    b.HasOne("FourierIT_API.Models.ClientEnlistment", "ClientEnlistment")
                        .WithOne("ClientRiskRating")
                        .HasForeignKey("FourierIT_API.Models.ClientRiskRating", "ClientEnlistmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientEnlistment");
                });

            modelBuilder.Entity("FourierIT_API.Models.Department", b =>
                {
                    b.HasOne("FourierIT_API.Models.Branch", "Branch")
                        .WithMany("Departments")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("FourierIT_API.Models.Document", b =>
                {
                    b.HasOne("FourierIT_API.Models.DocumentType", "DocumentType")
                        .WithMany("Documents")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FourierIT_API.Models.User", "User")
                        .WithMany("Documents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FourierIT_API.Models.DocumentBlob", b =>
                {
                    b.HasOne("FourierIT_API.Models.Document", "Document")
                        .WithOne("DocumentBlob")
                        .HasForeignKey("FourierIT_API.Models.DocumentBlob", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("FourierIT_API.Models.DocumentFicaRule", b =>
                {
                    b.HasOne("FourierIT_API.Models.DocumentType", "DocumentType")
                        .WithMany("DocumentFicaRules")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FourierIT_API.Models.FICARule", "FICARule")
                        .WithMany("DocumentFicaRules")
                        .HasForeignKey("FICARuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("FICARule");
                });

            modelBuilder.Entity("FourierIT_API.Models.DocumentStatusHistory", b =>
                {
                    b.HasOne("FourierIT_API.Models.Document", "Document")
                        .WithMany("DocumentStatusHistories")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("FourierIT_API.Models.EnquiryComment", b =>
                {
                    b.HasOne("FourierIT_API.Models.EnquiryFlag", "EnquiryFlag")
                        .WithMany("EnquiryComments")
                        .HasForeignKey("EnquiryFlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FourierIT_API.Models.User", "User")
                        .WithOne("EnquiryComment")
                        .HasForeignKey("FourierIT_API.Models.EnquiryComment", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnquiryFlag");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FourierIT_API.Models.EnquirySession", b =>
                {
                    b.HasOne("FourierIT_API.Models.AccessToken", "AccessToken")
                        .WithOne("EnquirySession")
                        .HasForeignKey("FourierIT_API.Models.EnquirySession", "TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessToken");
                });

            modelBuilder.Entity("FourierIT_API.Models.FICARuleHistory", b =>
                {
                    b.HasOne("FourierIT_API.Models.FICARule", "FICARule")
                        .WithMany("FICARuleHistories")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FICARule");
                });

            modelBuilder.Entity("FourierIT_API.Models.Institution", b =>
                {
                    b.HasOne("FourierIT_API.Models.InstitutionType", "InstitutionType")
                        .WithMany("Institutions")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InstitutionType");
                });

            modelBuilder.Entity("FourierIT_API.Models.InstitutionEnquiryRequest", b =>
                {
                    b.HasOne("FourierIT_API.Models.Institution", "Institution")
                        .WithMany("institutionEnquiryRequests")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("FourierIT_API.Models.InstitutionMembers", b =>
                {
                    b.HasOne("FourierIT_API.Models.Institution", "Institution")
                        .WithMany("InstitutionMembers")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FourierIT_API.Models.User", "User")
                        .WithMany("InstitutionMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FourierIT_API.Models.NotificationHistory", b =>
                {
                    b.HasOne("FourierIT_API.Models.Notification", "Notification")
                        .WithMany("NotificationHistories")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("FourierIT_API.Models.Profile", b =>
                {
                    b.HasOne("FourierIT_API.Models.Address", "Address")
                        .WithOne("Profile")
                        .HasForeignKey("FourierIT_API.Models.Profile", "AddressId");

                    b.HasOne("FourierIT_API.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("FourierIT_API.Models.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FourierIT_API.Models.RiskHistory", b =>
                {
                    b.HasOne("FourierIT_API.Models.ClientRiskRating", "ClientRiskRating")
                        .WithMany("RiskHistories")
                        .HasForeignKey("ClientRiskRatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientRiskRating");
                });

            modelBuilder.Entity("FourierIT_API.Models.RiskRatingVariable", b =>
                {
                    b.HasOne("FourierIT_API.Models.ClientRiskRating", "ClientRiskRating")
                        .WithMany("RiskRatingVariables")
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FourierIT_API.Models.RiskVariable", "RiskVariable")
                        .WithMany("RiskRatingVariables")
                        .HasForeignKey("RiskVariableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientRiskRating");

                    b.Navigation("RiskVariable");
                });

            modelBuilder.Entity("FourierIT_API.Models.Suburb", b =>
                {
                    b.HasOne("FourierIT_API.Models.City", "City")
                        .WithMany("Suburbs")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("FourierIT_API.Models.UserNotification", b =>
                {
                    b.HasOne("FourierIT_API.Models.Notification", "Notification")
                        .WithMany("UserNotifications")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FourierIT_API.Models.User", "User")
                        .WithMany("UserNotifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FourierIT_API.Models.UserSecurityQuestion", b =>
                {
                    b.HasOne("FourierIT_API.Models.SecurityQuestion", "SecurityQuestion")
                        .WithMany("UserSecurityQuestions")
                        .HasForeignKey("SecurityQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FourierIT_API.Models.User", "User")
                        .WithMany("UserSecurityQuestions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SecurityQuestion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FourierIT_API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FourierIT_API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FourierIT_API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FourierIT_API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FourierIT_API.Models.AccessToken", b =>
                {
                    b.Navigation("EnquirySession")
                        .IsRequired();
                });

            modelBuilder.Entity("FourierIT_API.Models.Address", b =>
                {
                    b.Navigation("Profile")
                        .IsRequired();
                });

            modelBuilder.Entity("FourierIT_API.Models.Branch", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("FourierIT_API.Models.City", b =>
                {
                    b.Navigation("Suburbs");
                });

            modelBuilder.Entity("FourierIT_API.Models.ClientEnlistment", b =>
                {
                    b.Navigation("ClientRiskRating")
                        .IsRequired();
                });

            modelBuilder.Entity("FourierIT_API.Models.ClientRiskRating", b =>
                {
                    b.Navigation("RiskHistories");

                    b.Navigation("RiskRatingVariables");
                });

            modelBuilder.Entity("FourierIT_API.Models.Document", b =>
                {
                    b.Navigation("AccessLists");

                    b.Navigation("CertificationDetails");

                    b.Navigation("DocumentBlob")
                        .IsRequired();

                    b.Navigation("DocumentStatusHistories");
                });

            modelBuilder.Entity("FourierIT_API.Models.DocumentBlob", b =>
                {
                    b.Navigation("BlobHistories");
                });

            modelBuilder.Entity("FourierIT_API.Models.DocumentType", b =>
                {
                    b.Navigation("DocumentFicaRules");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("FourierIT_API.Models.EnquiryFlag", b =>
                {
                    b.Navigation("AccessLists");

                    b.Navigation("EnquiryComments");
                });

            modelBuilder.Entity("FourierIT_API.Models.FICARule", b =>
                {
                    b.Navigation("DocumentFicaRules");

                    b.Navigation("FICARuleHistories");
                });

            modelBuilder.Entity("FourierIT_API.Models.Institution", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("ClientEnlistments");

                    b.Navigation("InstitutionMembers");

                    b.Navigation("institutionEnquiryRequests");
                });

            modelBuilder.Entity("FourierIT_API.Models.InstitutionEnquiryRequest", b =>
                {
                    b.Navigation("AccessLists");

                    b.Navigation("AccessToken")
                        .IsRequired();
                });

            modelBuilder.Entity("FourierIT_API.Models.InstitutionType", b =>
                {
                    b.Navigation("Institutions");
                });

            modelBuilder.Entity("FourierIT_API.Models.Notification", b =>
                {
                    b.Navigation("NotificationHistories");

                    b.Navigation("UserNotifications");
                });

            modelBuilder.Entity("FourierIT_API.Models.Province", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("FourierIT_API.Models.RiskVariable", b =>
                {
                    b.Navigation("RiskRatingVariables");
                });

            modelBuilder.Entity("FourierIT_API.Models.SecurityQuestion", b =>
                {
                    b.Navigation("UserSecurityQuestions");
                });

            modelBuilder.Entity("FourierIT_API.Models.Suburb", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("FourierIT_API.Models.User", b =>
                {
                    b.Navigation("AccessToken")
                        .IsRequired();

                    b.Navigation("ClientEnlistments");

                    b.Navigation("Documents");

                    b.Navigation("EnquiryComment")
                        .IsRequired();

                    b.Navigation("InstitutionMembers");

                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("UserNotifications");

                    b.Navigation("UserSecurityQuestions");
                });
#pragma warning restore 612, 618
        }
    }
}
